version: "3.9"

services:
  prometheus:
    image: prom/prometheus
    ports: 
      - "9090:9090"
    volumes:
      # 綁定prometheus內部的資料
      - ${PWD}/prometheus-storage:/prometheus
      # 使用自訂的prometheus.yml
      - ${PWD}/prometheus.yml:/etc/prometheus/prometheus.yml
    user: "1000:1000" # 需要使用user id，可以透過echo $UID 取得
    environment:
      - TZ=Asia/Taipei # 設定時間
  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    volumes:
      # 記得在localhost端修改權限，否則無法使用 sudo chown -R 472:472 grafana-storage
      - ${PWD}/grafana-storage:/var/lib/grafana
    environment:
      - TZ=Asia/Taipei
